namespace CMNetwork.Domain.Entities;

/// <summary>
/// Metadata for an audit evidence archive package (PDF/ZIP) generated by an
/// auditor. Files live on disk under wwwroot/evidence; this row records the
/// reference, who created it, and a SHA-256 checksum proving integrity.
/// </summary>
public class EvidenceArchive
{
    public Guid Id { get; set; }
    public string ArchiveNumber { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }

    /// <summary>Path relative to wwwroot, e.g. "evidence/2026/04/foo.zip".</summary>
    public string FilePath { get; set; } = string.Empty;
    public string FileName { get; set; } = string.Empty;
    public long FileSizeBytes { get; set; }
    public string ContentType { get; set; } = "application/zip";

    /// <summary>SHA-256 hex digest of the archive contents.</summary>
    public string Checksum { get; set; } = string.Empty;

    /// <summary>Number of audit log entries included in this archive.</summary>
    public int EntryCount { get; set; }

    /// <summary>JSON list of audit log Ids included.</summary>
    public string IncludedAuditLogIdsJson { get; set; } = "[]";

    public string GeneratedBy { get; set; } = string.Empty;
    public string? GeneratedByEmail { get; set; }
    public DateTime GeneratedUtc { get; set; }
}
